### PR TITLE
react promise is required

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by codeliner** [comment]
oh of course, even if the adapter is not able to handle a deferred. The interface requires it. Good catch

**Comment by bweston92** [comment]
Really because it internally is only checked when it is passed, php internally won't check the class even exists unless a argument is given?

—

**Comment by codeliner** [comment]
yeah, but you will get a fatal error instead of your exception. react/promise is a dependency of prooph/service-bus anyway

**Comment by bweston92** [comment]
You wouldn't get a fatal error, I just made this to double check my self https://3v4l.org/9a2to

**Comment by codeliner** [comment]
Damn, looks like you are right. @prolic revert?

**Comment by prolic** [comment]
No, It's a dependency, no matter if the instance of check works also
without it.
Am 26.09.2015 22:23 schrieb "Alexander Miertsch" notifications@github.com:

**Comment by codeliner** [comment]
@bweston92 zeromq supports [request / response scenarios](http://zguide.zeromq.org/page:all#Ask-and-Ye-Shall-Receive). We should add that feature. I've created an issue: https://github.com/prooph/psb-zeromq-producer/issues/5

So react/promise becomes a real dependency.

**Pull request merged**
